# Generated by Django 6.0.4 on 2026-04-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(choices=[('Groceries', 'Groceries'), ('Rent', 'Rent'), ('Electricity Bill', 'Electricity Bill'), ('Internet', 'Internet'), ('Movie', 'Movie'), ('Gym', 'Gym')], max_length=100),
        ),
    ]
